import sys
import os

# Add the scripts directory to the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from scripts.github_client import get_repo, post_review_comment
from scripts.diff_fetcher import fetch_pr_diff
from scripts.anthropic_client import call_anthropic_api
from scripts.config import Config

def main():
    print("🚀 Starting AI PR Review Process...")
    try:
        print(f"🔧 Repo: {Config.REPO_OWNER}/{Config.REPO_NAME}")
        print(f"🔢 PR Number: {Config.PR_NUMBER}")

        # Fetch the repository and PR diff
        repo = get_repo()
        diff_text = fetch_pr_diff(repo, Config.PR_NUMBER)
        print(f"📄 Diff length: {len(diff_text)}")

        # Call the Anthropic API for a review
        review_comment = call_anthropic_api(diff_text)
        print("📝 Review comment:\n", review_comment)

        # Echo the review to GitHub Actions logs
        print(f"::set-output name=review_comment::{review_comment}")

        if review_comment.strip():
            # Post review comment if available
            post_review_comment(repo.get_pull(Config.PR_NUMBER), review_comment)
            print("✅ Review process completed successfully.")
        else:
            print("⚠️ No review comment was generated by Claude.")

    except Exception as e:
        print(f"❌ Error during review: {e}")
